// Server-side rule data only. Never import this module into a browser bundle.
import type { CatalogRow, Kind, Rarity, SupplierId, SupplierRule, UpgradeId, UpgradeRule, DayEvent, Milestone } from './types.ts';
export const KINDS: Record<Kind, string> = { "tool": "工具", "artifact": "奇物", "bot": "机器人", "plant": "植物", "signal": "信号" };
export const RARITIES: Record<Rarity, string> = { "common": "普通", "rare": "稀有", "legendary": "传说" };
export const COLORS: Record<Rarity, string> = { "common": "#8ed4cb", "rare": "#b7a2ff", "legendary": "#ffd17a" };
export const CATALOG: CatalogRow[] = [["wrench", "折叠离子扳手", "common", "tool", 88, "一把能伸进四维螺孔的扳手。握柄留着某位机修师的名字。"], ["lamp", "重力手电", "common", "tool", 96, "照亮的地方会稍微变轻。请勿对着自己的鞋。"], ["coffee", "轨道咖啡壶", "common", "artifact", 105, "在失重时也能倒出完美一杯，不过上一任船长没洗它。"], ["cleaner", "哼歌清洁球", "common", "bot", 100, "会一边吸尘一边唱走调的远航民谣。"], ["moss", "瓶装月光苔", "common", "plant", 88, "关灯后发出湖蓝色微光，偶尔照出不存在的月亮。"], ["map", "二手星图仪", "common", "signal", 105, "标了很多餐馆和一个写着「千万别去」的小行星。"], ["music", "彗星玻璃八音盒", "rare", "artifact", 210, "每次彗星经过，它会多记住一个音符。"], ["welder", "逆相位焊笔", "rare", "tool", 195, "能焊好昨天断掉的零件，但说明书从明天开始写。"], ["bee", "迷路送信蜂", "rare", "bot", 225, "胸腔里藏着一张过期两百年的生日贺卡。"], ["seed", "低语星籽", "rare", "plant", 205, "靠近时能听到风穿过尚未长出的枝叶。"], ["dawn", "微型人造黎明", "legendary", "artifact", 480, "装在旧灯泡里的第一缕晨光，来自一颗已经熄灭的太阳。"], ["letter", "最后一封地球来信", "legendary", "signal", 520, "封面只有两个字：回家。信号仍在缓慢闪烁。"], ["compass", "逆风磁罗盘", "common", "signal", 93, "它总指向上一次说过再见的地方。"], ["kettle", "口袋气象瓶", "common", "artifact", 98, "瓶口飘出小小的天气预报，今天有糖霜雪。"], ["sprout", "慢半拍含羞草", "common", "plant", 91, "摸它一下，要等三秒钟才会害羞。"], ["snail", "快递蜗牛机", "common", "bot", 104, "从不超速，也从不投错门牌。"], ["clock", "午睡时间匣", "rare", "artifact", 230, "能把午后最安静的十分钟装进抽屉。"], ["needle", "真空缝星针", "rare", "tool", 215, "旧宇航服与小小的愿望，都能慢慢缝好。"], ["fern", "极光玻璃蕨", "rare", "plant", 225, "叶脉里流动着北方天空的颜色。"], ["radio", "潮汐回声电台", "rare", "signal", 240, "退潮时能收听一颗海洋星球的夜间节目。"], ["cat", "发条守夜猫", "rare", "bot", 235, "每天巡视货架，偶尔把价签拨到地上。"], ["hammer", "微型行星锻锤", "legendary", "tool", 500, "轻敲一下，火星便绕着锤头组成小小星系。"], ["tree", "永昼盆栽", "legendary", "plant", 490, "一棵不用等日出的树，也在等待一个家。"], ["whale", "袖珍巡航鲸", "legendary", "bot", 540, "会绕着店里的灯慢慢游，唱一首没有结尾的歌。"]];
export const SUPPLIERS: Record<SupplierId, SupplierRule> = { "salvage": { "id": "salvage", "name": "废轨回收站", "cost": 48, "stock": 4, "description": "平价漂流箱 · 普通 74% / 稀有 24% / 传说 2% · 品相 35–88" }, "curated": { "id": "curated", "name": "夜航商队", "cost": 110, "stock": 2, "description": "精选封存箱 · 普通 28% / 稀有 61% / 传说 11% · 品相 48–96" } };
export const UPGRADE_RULES: Record<UpgradeId, UpgradeRule> = { "workbench": { "name": "工作台", "costs": [70, 110, 260], "effects": ["基础修理：失手24%", "修理费减18%，失手14%", "修理费减36%，失手7%", "修理费减54%，失手3%"] }, "shelf": { "name": "货架", "costs": [65, 100, 240], "effects": ["7格货架 / 每日12精力", "10格货架 / 每日13精力", "13格货架 / 每日14精力", "16格货架 / 每日15精力"] }, "display": { "name": "展示柜", "costs": [120, 230, 420], "effects": ["朴素展示", "成交基础率+5百分点", "成交基础率+10百分点 / 多1位访客", "成交基础率+15百分点 / 多1位访客"] } };
export const SET_RULES: Record<Kind, [
    string,
    string
]> = { "tool": ["星港修理铺", "收藏3种工具，所有修理费再减4星币"], "artifact": ["小小宇宙馆", "收藏3种奇物，所有成交基础率+5百分点"], "bot": ["值夜小分队", "收藏3种机器人，每日精力+1"], "plant": ["窗边温室", "收藏3种植物，每日维护费减4星币"], "signal": ["远方的朋友", "收藏3种信号物品，回收箱每日供货+1"] };
export const EVENTS: DayEvent[] = [{ "id": "calm", "title": "平静靠港日", "description": "航道平稳，适合整理库存和照顾收藏。", "sale_multiplier": 1.0, "salvage_discount": 0, "repair_discount": 0, "cost_delta": 0, "energy_delta": 0 }, { "id": "meteor", "title": "流星回收潮", "description": "回收箱便宜8星币；忙碌的搬运让每日精力少1点。", "sale_multiplier": 1.0, "salvage_discount": 8, "repair_discount": 0, "cost_delta": 0, "energy_delta": -1 }, { "id": "festival", "title": "星灯夜市", "description": "成交基础率+10百分点；照明维护费多6星币。", "sale_multiplier": 1.12, "salvage_discount": 0, "repair_discount": 0, "cost_delta": 6, "energy_delta": 0 }, { "id": "workshop", "title": "机修师互助日", "description": "修理费减6星币；适合给有潜力的旧物第二次机会。", "sale_multiplier": 1.0, "salvage_discount": 0, "repair_discount": 6, "cost_delta": 0, "energy_delta": 0 }, { "id": "fog", "title": "星云浓雾", "description": "来客更谨慎，成交基础率-10百分点；港务处减免4星币维护费。", "sale_multiplier": 0.9, "salvage_discount": 0, "repair_discount": 0, "cost_delta": -4, "energy_delta": 0 }, { "id": "tailwind", "title": "顺风补给日", "description": "物流顺畅，每日精力+1，今天可以多做一件事。", "sale_multiplier": 1.0, "salvage_discount": 0, "repair_discount": 0, "cost_delta": 0, "energy_delta": 1 }];
export const CUSTOMERS: [
    string,
    string,
    string,
    Kind,
    number,
    number,
    number
][] = [["mira", "米拉", "星港机修师", "tool", 45, 130, 340], ["nox", "诺克斯", "旧梦收藏家", "artifact", 65, 180, 620], ["pip", "皮普", "机器人护理员", "bot", 40, 150, 430], ["luna", "露娜", "轨道园艺师", "plant", 60, 160, 440], ["echo", "回声", "远航信号员", "signal", 55, 170, 600], ["sol", "索尔", "随船修补匠", "tool", 30, 100, 260], ["ayu", "阿鱼", "夜航讲故事的人", "artifact", 35, 120, 390], ["bo", "波波", "流浪机偶导演", "bot", 70, 220, 650]];
export const MILESTONES: Milestone[] = [{ "id": "first_week", "title": "首周站稳脚跟", "description": "第7天闭店后检查；未达标也能继续，之后补齐。", "min_condition": 70, "targets": { "credits": 650, "collection": 2 } }, { "id": "neighborhood", "title": "街区熟面孔", "description": "积累客源，拓展收藏，并为店铺作长远投资。", "min_condition": 75, "targets": { "credits": 1400, "collection": 5, "reputation": 12, "upgrades": 2, "collection_categories": 3 } }, { "id": "lighthouse", "title": "夜航灯塔", "description": "让旅客为了这间小店，愿意在星港多停一天。", "min_condition": 80, "targets": { "credits": 2800, "collection": 9, "reputation": 25, "upgrades": 4, "quality_themes": 1 } }, { "id": "landmark", "title": "星港地标", "description": "经营与收藏都留下自己的名字。", "min_condition": 85, "targets": { "credits": 5000, "collection": 15, "reputation": 40, "upgrades": 6, "collection_categories": 5, "quality_themes": 3 } }];
export const TRADE_RULES = { "die": "D100", "dice": ["D10 tens 00–90", "D10 ones 0–9"], "direction": "roll_low", "zero_zero": 100, "critical": 1, "fumble": 100, "critical_rule": "01一见钟情，突破普通意愿和预算，按合法报价成交", "fumble_rule": "100大失败，本日该货接待立即结束", "house_rules": "CoC启发的简化房规，非官方完整规则", "max_rolls_per_item_day": 2, "price_limit": 9999, "final_offer_energy": 1, "final_offer_rule": "counter_offer < price < original_price", "final_chance_formula": "clamp(1,99,floor(clamp(1,99,70+bonus)*counter/(2*price-counter)))", "initial_chance_formula": "clamp(1,99,floor(clamp(1,99,60+bonus-50*log2(price/reference))/(1+2*max(0,price/budget-1))))", "initial_budget_rule": "预算是隐藏的日常消费舒适线，不是购买力硬上限；超过后成功率随相对超额平滑下降，初次精确概率不预告", "counter_rule": "普通失败须标价≤公开参考价125%且≤公开预算上限，并符合类别/品相；否则离店；01仍必成", "walkin_daily_limit": 1, "walkin_budget_range": [60, 120], "walkin_min_condition": 45, "final_budget_rule": "还价已反映预算，最终报价不再施加隐藏预算门槛", "endday": "自动谢绝未完成还价", "miracle_probability": 0.01 };
